-- ============================================================
-- New Wheels: Data Querying and Analytics with SQL
-- 10 business questions answered via SQL against the New Wheels
-- transactional database (customer_t, order_t, product_t)
-- ============================================================

-- Question 1: Find the total number of customers who have placed
-- orders. What is the distribution of the customers across states?
SELECT
    c.state,
    COUNT(c.customer_id) AS num_customers
FROM customer_t c
GROUP BY c.state
ORDER BY num_customers DESC;


-- Question 2: Which are the top 5 vehicle makers preferred by the
-- customers?
SELECT
    p.vehicle_maker,
    COUNT(DISTINCT o.customer_id) AS num_customers
FROM order_t o
JOIN product_t p ON o.product_id = p.product_id
GROUP BY p.vehicle_maker
ORDER BY num_customers DESC
LIMIT 5;


-- Question 3: Which is the most preferred vehicle maker in each state?
WITH ranked AS (
    SELECT
        c.state,
        p.vehicle_maker,
        COUNT(DISTINCT o.customer_id) AS num_customers,
        RANK() OVER (
            PARTITION BY c.state
            ORDER BY COUNT(DISTINCT o.customer_id) DESC
        ) AS rnk
    FROM order_t o
    JOIN customer_t c ON o.customer_id = c.customer_id
    JOIN product_t p ON o.product_id = p.product_id
    GROUP BY c.state, p.vehicle_maker
)
SELECT state, vehicle_maker, num_customers
FROM ranked
WHERE rnk = 1
ORDER BY state;


-- Question 4: Find the overall average rating given by the customers.
-- What is the average rating in each quarter? Consider the following
-- mapping for ratings: "Very Bad": 1, "Bad": 2, "Okay": 3, "Good": 4,
-- "Very Good": 5

-- Overall average rating
SELECT
    AVG(
        CASE customer_feedback
            WHEN 'Very Bad'  THEN 1
            WHEN 'Bad'       THEN 2
            WHEN 'Okay'      THEN 3
            WHEN 'Good'      THEN 4
            WHEN 'Very Good' THEN 5
        END
    ) AS overall_avg_rating
FROM order_t;

-- Average rating by quarter
SELECT
    quarter_number,
    ROUND(AVG(
        CASE customer_feedback
            WHEN 'Very Bad'  THEN 1
            WHEN 'Bad'       THEN 2
            WHEN 'Okay'      THEN 3
            WHEN 'Good'      THEN 4
            WHEN 'Very Good' THEN 5
        END
    ), 2) AS avg_rating
FROM order_t
GROUP BY quarter_number
ORDER BY quarter_number;


-- Question 5: Find the percentage distribution of feedback from the
-- customers. Are customers getting more dissatisfied over time?
SELECT
    quarter_number,
    ROUND(100.0 * SUM(CASE WHEN customer_feedback = 'Very Bad'  THEN 1 ELSE 0 END) / COUNT(*), 2) AS pct_very_bad,
    ROUND(100.0 * SUM(CASE WHEN customer_feedback = 'Bad'       THEN 1 ELSE 0 END) / COUNT(*), 2) AS pct_bad,
    ROUND(100.0 * SUM(CASE WHEN customer_feedback = 'Okay'      THEN 1 ELSE 0 END) / COUNT(*), 2) AS pct_okay,
    ROUND(100.0 * SUM(CASE WHEN customer_feedback = 'Good'      THEN 1 ELSE 0 END) / COUNT(*), 2) AS pct_good,
    ROUND(100.0 * SUM(CASE WHEN customer_feedback = 'Very Good' THEN 1 ELSE 0 END) / COUNT(*), 2) AS pct_very_good
FROM order_t
GROUP BY quarter_number
ORDER BY quarter_number;


-- Question 6: What is the trend of the number of orders by quarter?
SELECT
    quarter_number,
    COUNT(order_id) AS num_orders
FROM order_t
GROUP BY quarter_number
ORDER BY quarter_number;


-- Question 7: Calculate the net revenue generated by the company.
-- What is the quarter-over-quarter % change in net revenue?
WITH revenue AS (
    SELECT
        quarter_number,
        ROUND(SUM(quantity * vehicle_price * (1 - discount)), 2) AS net_revenue
    FROM order_t
    GROUP BY quarter_number
)
SELECT
    quarter_number,
    net_revenue,
    LAG(net_revenue) OVER (ORDER BY quarter_number) AS prev_quarter_revenue,
    ROUND(
        (net_revenue - LAG(net_revenue) OVER (ORDER BY quarter_number))
        * 100.0 / LAG(net_revenue) OVER (ORDER BY quarter_number),
    2) AS qoq_pct_change
FROM revenue
ORDER BY quarter_number;


-- Question 8: What is the trend of net revenue and orders by quarters?
SELECT
    quarter_number,
    ROUND(SUM(quantity * vehicle_price * (1 - discount)), 2) AS net_revenue,
    COUNT(order_id) AS num_orders
FROM order_t
GROUP BY quarter_number
ORDER BY quarter_number;


-- Question 9: What is the average discount offered for different
-- types of credit cards?
SELECT
    c.credit_card_type,
    ROUND(AVG(o.discount) * 100, 2) AS avg_discount_pct
FROM order_t o
JOIN customer_t c ON o.customer_id = c.customer_id
GROUP BY c.credit_card_type
ORDER BY avg_discount_pct DESC;


-- Question 10: What is the average time taken to ship the placed
-- orders for each quarter?
SELECT
    quarter_number,
    ROUND(AVG(julianday(ship_date) - julianday(order_date)), 2) AS avg_days_to_ship
FROM order_t
GROUP BY quarter_number
ORDER BY quarter_number;
